"""
Wan VACE Prep - Custom nodes for preparing videos for Wan VACE generation
"""

from .vace_join import NODE_CLASS_MAPPINGS as JOIN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JOIN_DISPLAY
from .vace_extend import NODE_CLASS_MAPPINGS as EXTEND_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EXTEND_DISPLAY
from .load_videos_from_folder import NODE_CLASS_MAPPINGS as LOAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY
from .vace_batch_context import NODE_CLASS_MAPPINGS as CONTEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONTEXT_DISPLAY
from .frame_number_overlay import NODE_CLASS_MAPPINGS as OVERLAY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OVERLAY_DISPLAY
from .vace_outpaint import NODE_CLASS_MAPPINGS as OUTPAINT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OUTPAINT_DISPLAY
NODE_CLASS_MAPPINGS = {**JOIN_MAPPINGS, **EXTEND_MAPPINGS, **LOAD_MAPPINGS, **CONTEXT_MAPPINGS, **OVERLAY_MAPPINGS, **OUTPAINT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**JOIN_DISPLAY, **EXTEND_DISPLAY, **LOAD_DISPLAY, **CONTEXT_DISPLAY, **OVERLAY_DISPLAY, **OUTPAINT_DISPLAY}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]